#!/usr/bin/env sh
useradd -s /bin/bash $1
mkdir -p  /home/$1/.ssh/
cp -r ~/.ssh/authorized_keys /home/$1/.ssh/authorized_keys
chmod 700 /home/$1/.ssh
chmod 600 /home/$1/.ssh/authorized_keys
chown -R $1 /home/$!
